import type { Metadata } from 'next'
import {
    ClerkProvider,
} from '@clerk/nextjs'
import './globals.css'
import {dark} from "@clerk/themes";

export const metadata: Metadata = {
    title: 'Clerk Next.js Quickstart',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <ClerkProvider
        appearance={{
            baseTheme: dark
        }}>
            <html lang="en">
            <body className={`antialiased`}>
            {children}
            </body>
            </html>
        </ClerkProvider>
    )
}